[package]
name = "ajour-core"
description = "Core library for Ajour"
version = "0.4.1"
authors = ["Casper Rogild Storm"]
license = "MIT"
homepage = "https://github.com/casperstorm/ajour"
repository = "https://github.com/casperstorm/ajour"
edition = "2018"

[features]
gui = ['iced_native']

[[bin]]
name = "file_parsing_regex"

[[bin]]
name = "fingerprint_addon"

[[bin]]
name = "parse_addon_directory"

[[bin]]
name = "parse_toc"

[dependencies]
regex = "1.3.9"
fancy-regex = "0.3.5" # Regex with backtracking
async-std = "1.6.2"
dirs = "3.0"
serde = { version = "1.0.114", features=['derive'] }
serde_yaml = "0.8.13"
serde_json = "1.0.57"
isahc = { version = "0.9.6", features = ["json"] }
zip = "0.5.6"
glob = "0.3.0"
rayon = "1.4.0"
lazy_static = "1.4.0"
chrono = "0.4"
log = "0.4"
fern = "0.6"
walkdir = "2.3"

iced_native = { git = "https://github.com/hecrj/iced.git", rev = "fb015a85d22a7c4632bd251127a89259bfd0c346", optional = true }
